<?php

namespace Api\RemoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends CrudRepository
{
    /**
     * Find one Account entity by its username and password.
     * @param string $username The username of the Account.
     * @param string $password The encoded password of the Account.
     * @return Account|null The account that was found.
     */
    public function findByUsernameAndPassword($username, $password) {
        $criteria = array(
            'username' => $username,
            'password' => $password
        );

        return $this->findOneBy($criteria);
    }
}
