<?php

namespace Api\RemoteBundle\Entity;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationKeyRepository extends EntityRepository implements CrudInterface
{
    /**
     * {@inheritDoc}
     */
    public function create($params) {
        $appKey = new ApplicationKey();

        $appKey->setName($params['name']);
        $appKey->setValue($params['value']);

        $this->_em->persist($appKey);
        $this->_em->flush();

        return $appKey->getId();
    }

    /**
     * {@inheritDoc}
     */
    public function update($id, $params) {
        $appKey = $this->find($id);

        if (!$appKey) {
            throw new EntityNotFoundException('No application key found for id '.$id);
        }

        $appKey->setName($params['name']);
        $appKey->setValue($params['value']);

        $this->_em->flush();

        return $appKey->getId();
    }

    /**
     * {@inheritDoc}
     */
    public function delete($id) {
        $appKey = $this->find($id);

        if (!$appKey) {
            throw new EntityNotFoundException('No application key found for id '.$id);
        }

        $this->_em->remove($appKey);
        $this->_em->flush();

        return true;
    }
}
