<?php

namespace Api\RemoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends CrudRepository
{
    public function retrieveAll() {
        $query = $this->_em->createQueryBuilder('p')
            ->select('c')
            ->from('ApiRemoteBundle:Category', 'c')
            ->orderBy('c.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
