<?php

namespace Api\RemoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends CrudRepository
{
    public function retrieveForSubcategory($subId) {
        $query = $this->_em->createQueryBuilder('q')
            ->select('p')
            ->from('ApiRemoteBundle:Product', 'p')
            ->where('p.subcategory = :id')
            ->orderBy('p.name','ASC')
            ->setParameter('id', $subId)
            ->getQuery();

        return $query->getResult();
    }
}
