<?php

namespace Api\RemoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends CrudRepository
{
    public function retrieveAll() {
        $query = $this->_em->createQueryBuilder('p')
            ->select('s')
            ->from('ApiRemoteBundle:Subcategory', 's')
            ->orderBy('s.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
