parameters:
#    api_remote.example.class: Api\RemoteBundle\Example

services:
  api.tokens.action_listener:
    class: Api\RemoteBundle\EventListener\TokenListener
    arguments: [ @token.verification ]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  account:
    class: Api\RemoteBundle\Service\AccountService
    arguments: [ @doctrine.orm.entity_manager ]

  category:
    class: Api\RemoteBundle\Service\CategoryService
    arguments: [ @doctrine.orm.entity_manager ]

  subcategory:
    class: Api\RemoteBundle\Service\SubcategoryService
    arguments: [ @doctrine.orm.entity_manager ]

  json:
    class: Api\RemoteBundle\Service\JsonProcessorService

  token.verification:
    class: Api\RemoteBundle\Service\TokenVerificationService
    arguments: [ @doctrine.orm.entity_manager ]