# Shop Routes
shop_content_homepage:
    pattern:  /
    defaults: { _controller: ShopContentBundle:Content:home }

shop_account_login:
    pattern: /account/login
    defaults: { _controller: ShopContentBundle:Account:login }

shop_account_logout:
    pattern: /account/logout
    defaults: { _controller: ShopContentBundle:Account:logout }

shop_account_register:
    pattern: /account/register
    defaults: { _controller: ShopContentBundle:Account:register }

shop_account_index:
    pattern: /account
    defaults: { _controller: ShopContentBundle:Account:index }

shop_about_index:
    pattern: /about
    defaults: { _controller: ShopContentBundle:Content:about}

shop_contact_index:
    pattern: /contact
    defaults: { _controller: ShopContentBundle:Content:contact }

shop_cart_index:
    pattern: /cart
    defaults: { _controller: ShopContentBundle:Cart:index }

shop_product_item:
    pattern: /product/{name}/{id}
    defaults: { _controller: ShopContentBundle:Product:item }

shop_category_listing:
    pattern: /category/{name}/{id}
    defaults: { _controller: ShopContentBundle:Product:category }

shop_subcategory_listing:
    pattern: /subcategory/{name}/{id}
    defaults: { _controller: ShopContentBundle:Product:subcategory }

# Api Routes
api_account_login:
    pattern:  api/account/login
    methods: [POST]

api_account_register:
    pattern: api/account/register
    methods: [POST]

api_category_retrieve:
    pattern: api/category/retrieveAll
    methods: [POST]

api_subcategory_find_parent:
    pattern: api/subcategory/retrieveParentOfSubcategory
    methods: [POST]

api_subcategory_retrieve_one:
    pattern: api/subcategory/findOne
    methods: [POST]

api_category_retrieve_one:
    pattern: api/category/findOne
    methods: [POST]

api_product_retrieve_subcategory:
    pattern: api/product/retrieveForSubcategory
    methods: [POST]

api_product_retrieve_category:
    pattern: api/product/retrieveForCategory
    methods: [POST]