# Shop Routes
shop_content_homepage:
    pattern:  /
    defaults: { _controller: ShopContentBundle:Content:home }

shop_account_login:
    pattern: /account/login
    defaults: { _controller: ShopContentBundle:Account:login }

shop_account_logout:
    pattern: /account/logout
    defaults: { _controller: ShopContentBundle:Account:logout }

shop_account_register:
    pattern: /account/register
    defaults: { _controller: ShopContentBundle:Account:register }

shop_account_index:
    pattern: /account
    defaults: { _controller: ShopContentBundle:Account:index }

shop_about_index:
    pattern: /about
    defaults: { _controller: ShopContentBundle:Content:about}

shop_contact_index:
    pattern: /contact
    defaults: { _controller: ShopContentBundle:Content:contact }

shop_cart_index:
    pattern: /cart
    defaults: { _controller: ShopContentBundle:Cart:index }

# Api Routes
api_account_login:
    pattern:  api/account/login
    defaults: { _controller: ApiRemoteBundle:Account:login }
    methods: [POST]

api_account_register:
    pattern: api/account/register
    defaults: { _controller: ApiRemoteBundle:Account:register }
    methods: [POST]