parameters:
#    shop_content.example.class: Shop\ContentBundle\Example

services:
#    shop_content.example:
#        class: %shop_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  api.call:
    class: Shop\ContentBundle\Service\ApiCallService
    arguments:
      router: "@router"
      buzz: "@buzz"
      appKey: %app_key%

  json.response:
    class: Shop\ContentBundle\Service\JsonResponseService